In [49]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
import re

In [4]:
data = pd.read_csv("tripadvisor_hotel_reviews.csv")

In [5]:
data.info

<bound method DataFrame.info of                                                 Review  Rating
0    nice hotel expensive parking got good deal sta...       4
1    ok nothing special charge diamond member hilto...       2
2    nice rooms not 4* experience hotel monaco seat...       3
3    unique, great stay, wonderful time hotel monac...       5
4    great stay great stay, went seahawk game aweso...       5
..                                                 ...     ...
104  fairmont hotel singapore splendid, stayed fair...       5
105  great hotel stayed hotel night route perth chr...       4
106  great hotel centre stayed 5 nights room overlo...       4
107  great location great value great hotel husband...       5
108  lovely hotel great location stayed vacation to...       5

[109 rows x 2 columns]>

In [6]:
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [8]:
data['Review'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews did valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe just noisy neighbors, aveda bath products nice, did not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience having pay 40 parking night,  '

In [16]:
data.drop('Review Lowercase', axis=1, inplace=True)

In [19]:
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [20]:
data['review_lowercase'] = data['Review'].str.lower()

In [21]:
data.head()

                                              Review  Rating                                   review_lowercase
0  nice hotel expensive parking got good deal sta...       4  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...       2  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...       3  nice rooms not 4* experience hotel monaco seat...
3  unique, great stay, wonderful time hotel monac...       5  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...       5  great stay great stay, went seahawk game aweso...

In [22]:
en_stopwords = stopwords.words('english')

In [23]:
en_stopwords.remove('not')

In [25]:
data['review_no_stopwords'] = data['review_lowercase'].apply(lambda x : ' '.join([word for word in x.split() if word not in en_stopwords]))

In [26]:
data['review_no_stopwords'].head()

0    nice hotel expensive parking got good deal sta...
1    ok nothing special charge diamond member hilto...
2    nice rooms not 4* experience hotel monaco seat...
3    unique, great stay, wonderful time hotel monac...
4    great stay great stay, went seahawk game aweso...
Name: review_no_stopwords, dtype: object

In [27]:
data['review_no_stopwords'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe noisy neighbors, aveda bath products nice, not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience pay 40 parking night,'

In [29]:
data['review_no_stop_no_punc'] = data.apply(lambda x : re.sub(r"[*]", "star", x["review_no_stopwords"]), axis=1)

In [30]:
data.head()

                                              Review  ...                             review_no_stop_no_punc
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4star experience hotel monaco s...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 5 columns]

In [31]:
data['review_no_stop_no_punc'] = data.apply(lambda x : re.sub(r"[^\w\s]", "", x["review_no_stop_no_punc"]), axis=1)

In [32]:
data['review_no_stop_no_punc'][0]

'nice hotel expensive parking got good deal stay hotel anniversary arrived late evening took advice previous reviews valet parking check quick easy little disappointed nonexistent view room room clean nice size bed comfortable woke stiff neck high pillows not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway maybe noisy neighbors aveda bath products nice not goldfish stay nice touch taken advantage staying longer location great walking distance shopping overall nice experience pay 40 parking night'

In [34]:
data['tokenized'] = data.apply(lambda x : word_tokenize(x['review_no_stop_no_punc']), axis=1)

In [35]:
data['tokenized'][0]

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'reviews',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillows',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bangs',
 'doors',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbors',
 'aveda',
 'bath',
 'products',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night']

In [36]:
ps = PorterStemmer()

In [38]:
data['stemmed'] = data['tokenized'].apply(lambda x : [ps.stem(word) for word in x])

In [39]:
data['stemmed'][0]

['nice',
 'hotel',
 'expens',
 'park',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversari',
 'arriv',
 'late',
 'even',
 'took',
 'advic',
 'previou',
 'review',
 'valet',
 'park',
 'check',
 'quick',
 'easi',
 'littl',
 'disappoint',
 'nonexist',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfort',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillow',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morn',
 'loud',
 'bang',
 'door',
 'open',
 'close',
 'hear',
 'peopl',
 'talk',
 'hallway',
 'mayb',
 'noisi',
 'neighbor',
 'aveda',
 'bath',
 'product',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantag',
 'stay',
 'longer',
 'locat',
 'great',
 'walk',
 'distanc',
 'shop',
 'overal',
 'nice',
 'experi',
 'pay',
 '40',
 'park',
 'night']

In [40]:
lemmatizer = WordNetLemmatizer()

In [41]:
data['lemmatized'] = data['tokenized'].apply(lambda x : [lemmatizer.lemmatize(word) for word in x])

In [43]:
data.lemmatized[0]

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'review',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillow',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bang',
 'door',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbor',
 'aveda',
 'bath',
 'product',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night']

In [44]:
tokens_clean = sum(data['lemmatized'], [])

In [50]:
unigrams = pd.Series(nltk.ngrams(tokens_clean, 1)).value_counts()

In [51]:
unigrams

(hotel,)           292
(room,)            275
(great,)           126
(not,)             122
(stay,)             95
                  ...
(175,)               1
(smackagainst,)      1
(2x,)                1
(80,)                1
(connected,)         1
Name: count, Length: 2589, dtype: int64

In [52]:
bigrams =  pd.Series(nltk.ngrams(tokens_clean, 2)).value_counts()

In [53]:
bigrams

(great, location)     24
(space, needle)       21
(hotel, monaco)       16
(great, hotel)        12
(staff, friendly)     12
                      ..
(didnt, make)          1
(personnel, didnt)     1
(minute, stay)         1
(starting, minute)     1
(food, raffle)         1
Name: count, Length: 8263, dtype: int64